In [4]:
import pandas as pd

# read CSV
# inspect rows
# filter data
# count records
# analyze columns
# clean data
# prepare datasets

In [5]:
sample_path = r"C:\Users\sujat\.cache\kagglehub\datasets\thoughtvector\customer-support-on-twitter\versions\10\sample.csv"

df = pd.read_csv(sample_path)

df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0

In [6]:
df.shape

(93, 7)

In [7]:
df.columns.tolist()

['tweet_id',
 'author_id',
 'inbound',
 'created_at',
 'text',
 'response_tweet_id',
 'in_response_to_tweet_id']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tweet_id                 93 non-null     int64
 1   author_id                93 non-null     object
 2   inbound                  93 non-null     bool
 3   created_at               93 non-null     object
 4   text                     93 non-null     object
 5   response_tweet_id        65 non-null     object
 6   in_response_to_tweet_id  68 non-null     float64
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 4.6+ KB

In [9]:
df.isnull().sum()

tweet_id                    0
author_id                   0
inbound                     0
created_at                  0
text                        0
response_tweet_id          28
in_response_to_tweet_id    25
dtype: int64

In [10]:
df.head(10)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0
5,119243,VirginTrains,False,Tue Oct 10 15:25:14 +0000 2017,"@105836 Have you tried from another device, Mi...",119244,119241.0
6,119244,105836,True,Tue Oct 10 15:26:44 +0000 2017,"@VirginTrains yep, I've tried laptop too sever...",119245,119243.0
7,119245,VirginTrains,False,Tue Oct 10 15:33:22 +0000 2017,"@105836 It's working OK from here, Miriam. Doe...",NaN,119244.0
8,119242,105836,True,Tue Oct 10 15:09:00 +0000 2017,@VirginTrains I still haven't heard &amp; the ...,119240,119246.0
9,119246,VirginTrains,False,Tue Oct 10 10:13:19 +0000 2017,@105836 That's what we're here for Miriam 😊 T...,119242,119247.0

In [11]:
df["text"].head(10).tolist()

['@AppleSupport causing the reply to be disregarded and the tapped notification under the keyboard is opened😡😡😡',
 '@105835 Your business means a lot to us. Please DM your name, zip code and additional details about your concern. ^RR https://t.co/znUu1VJn9r',
 "@76328 I really hope you all change but I'm sure you won't! Because you don't have to!",
 '@105836 LiveChat is online at the moment - https://t.co/SY94VtU8Kq or contact 03331 031 031 option 1, 4, 3 (Leave a message) to request a call back',
 "@VirginTrains see attached error message. I've tried leaving a voicemail several times in the past week https://t.co/NxVZjlYx1k",
 '@105836 Have you tried from another device, Miriam ^MM',
 "@VirginTrains yep, I've tried laptop too several times over the past week and again today. I've tried different browsers too",
 "@105836 It's working OK from here, Miriam. Does this link help https://t.co/0m2mpH15eh ? ^MM",
 "@VirginTrains I still haven't heard &amp; the number I'm directed to by phone is a dead end &amp; the live chat doesn't work. Can someone call me?",
 "@105836 That's what we're here for Miriam 😊  The team should send you an email shortly ^HP"]

In [6]:
df["inbound"].value_counts()

inbound
True     49
False    44
Name: count, dtype: int64

In [9]:
df[df["inbound"] == True][
    ["tweet_id", "author_id", "text"]
]

    tweet_id author_id                                               text
0     119237    105834  @AppleSupport causing the reply to be disregar...
2     119239    105835  @76328 I really hope you all change but I'm su...
4     119241    105836  @VirginTrains see attached error message. I've...
6     119244    105836  @VirginTrains yep, I've tried laptop too sever...
8     119242    105836  @VirginTrains I still haven't heard &amp; the ...
11    119249    105837  @105838 @AppleSupport Me too am suffering , ho...
12    119250    105838  @AppleSupport hi #apple, I’ve a concern about ...
14    119253    105839  I just updated my phone and suddenly everythin...
16    119255    105840  @SpotifyCares Thanks! Version 8.4.22.857 armv7...
18    119258    105840  @SpotifyCares No, but I've moved speaker to ab...
20    119260    105840                   @SpotifyCares Brilliant thanks 😊
22    119256    105840  @76495 @91226 Please help! Spotify Premium ski...
24    119263    105841  @AppleSupport after the 11.0.2 my phone just s...
26    119265    105842  First flight for long time with @British_Airwa...
28    119268    105843  Okay @76099 I used my fucking phone for 2 minu...
30    119270    105844  @AppleSupport Can you get my iPhone 7plus back...
32    119272    105844  You’ve paralysed my phone with your update @76...
34    119274     82476  @O2 I received this a few weeks ago, since the...
36    119276    105845  My internet is down and xfinity talkin about 2...
38    119278    105676  @76803  I service last 40 min sprint can I get...
40    119280    105846  So the new @76099 update does not let me liste...
42    119282    105847  @SpotifyCares seems to be working at this stag...
44    119285    105847  @SpotifyCares problem has come back again toda...
46    119287    105847  @SpotifyCares It's on a Macbook Air (early 201...
48    119283    105847  @SpotifyCares i've been having issues with pla...
50    119290    105848  @AppleSupport Latest version 😡😡 I have read th...
51    119291    105848  @AppleSupport Super help - problem solved 😀 on...
52    119292    105848  @AppleSupport #ios11update - is still killing ...
54    119294    105849  Took my phone off charge at 7:20am.\n\n8:03am ...
56    119296    105850     @SouthwestAir I am! Thank you for the answer!!
57    119297    105850  @southwestair Just curious....will I get the c...
59    119299    105851  @AppleSupport I need a new code for my I-store...
61    119301    105852  @76099 @AppleSupport fix this update. It’s hor...
63    119302    105842  @British_Airways Thanks for your answer. Respo...
66    119305    105854  @Ask_Spectrum It's just in my yard. I've calle...
67    119306    105854  @76501 I guess this means free cable for the n...
69    119309    105855          @Tesco Maybe hire colleagues who can see?
70    119310    105855  @Tesco The point is if it's enforced they do i...
72    119313    105855             @Tesco Uk offlicense law is 18. Not 25
74    119315    105855  Got id's @Tesco for buying one Adnams Broadsid...
76    119318    105856  @Tesco Will I lose all the shopping I've done ...
78    119321    105856  @Tesco Done all that. Still telling me there a...
80    119319    105856  Hey @Tesco, your website's broken. It's tellin...
82    119324    105857  @AppleSupport I have the latest version iOS. I...
84    119326    105857  My apps stop working without warning and my ph...
86    119328    105858  @HPSupport Problem with printhead  Serial# TH5...
88    119330    105859  @105860 I wish Amazon had an option of where I...
89    119331    105860  They reschedule my shit for tomorrow https://t...
91    119333    105861  @Tesco bit of both - finding the layout cumber...

In [10]:
df[df["inbound"] == False][
    ["tweet_id", "author_id", "text"]
]

,tweet_id,author_id,text
1,119238,ChaseSupport,@105835 Your business means a lot to us. Pleas...
3,119240,VirginTrains,@105836 LiveChat is online at the moment - htt...
5,119243,VirginTrains,"@105836 Have you tried from another device, Mi..."
7,119245,VirginTrains,"@105836 It's working OK from here, Miriam. Doe..."
9,119246,VirginTrains,@105836 That's what we're here for Miriam 😊 T...
10,119248,AppleSupport,@105837 We can help. Which version of iOS are ...
13,119252,AppleSupport,@105839 Thanks for reaching out to us. We are ...
15,119254,SpotifyCares,@105840 Hi there! What device is this happenin...
17,119257,SpotifyCares,@105840 Thanks. The distance could possibly af...
19,119259,SpotifyCares,@105840 That's great to hear. If anything come...
21,119261,SpotifyCares,@105840 You're welcome! If there's anything el...
23,119262,AppleSupport,@105841 We'd love to help! Please DM us and le...
25,119264,British_Airways,@105842 We're sorry your flight has been delay...
27,119267,AppleSupport,"@105843 Battery life is important, and we're h..."
29,119269,AppleSupport,@105844 Thanks for reaching out to us. We are ...
31,119271,AppleSupport,@105844 We'd be happy to help. Send us a DM an...
33,119273,O2,"@82476 🤔 We'd like to help Sam, which number i..."
35,119275,comcastcares,@105845 I understand this is a frustrating exp...
37,119277,sprintcare,@105676 I understand how you frustrated this s...
39,119279,AppleSupport,@105846 We'd like to help. What happens when y...
41,119281,SpotifyCares,@105847 Hi Harry! Help's here. Can you check i...
43,119284,SpotifyCares,@105847 Sure thing. We'll keep an eye out for ...
45,119286,SpotifyCares,@105847 Thanks for giving us a nudge about thi...
47,119288,SpotifyCares,@105847 Got it. Can you try the steps here for...
49,119289,AppleSupport,@105848 Let's take a look. What is the exact i...
53,119293,AppleSupport,@105849 Thanks for reaching out to us. We are ...
55,119295,SouthwestAir,@105850 Once the points load and you hit the n...
58,119298,AppleSupport,@105851 We'd like to provide some assistance w...
60,119300,AppleSupport,@105852 Are you experiencing an issue with you...
62,119266,British_Airways,"@105842 I appreciate it's after 15:30 now, so ..."
64,119303,British_Airways,@105842 Very sorry to hear this. We hope you ...
65,119304,Ask_Spectrum,@105854 I am sorry for the poor experience. Ca...
68,119308,Tesco,"@105855 Hi Thomas, if a colleague believes the..."
71,119311,Tesco,"@105855 Hi Thomas, this is correct but this he..."
73,119314,Tesco,"@105855 Hi Thomas, we operate a Think 25 polic..."
75,119317,Tesco,"@105856 Hi there, could you try deleting your ..."
77,119320,Tesco,"@105856 Hi there, as long as you sign out of y..."
79,119322,Tesco,"@105856 Can you DM me your full name, address ..."
81,119323,AppleSupport,@105857 Is there a particular app that seems t...
83,119325,AppleSupport,@105857 We'd like to help if we can. When did ...
85,119327,HPSupport,"@105858 Hi Agoura, thanks for tweeting. Please..."
87,119329,UPSHelp,@105859 UPS has a service called My Choice tha...
90,119332,Tesco,"@105861 Hey Sara, sorry to hear of the issues ..."
92,119335,Tesco,@105861 If that doesn't help please DM your fu...

In [11]:
from collections import Counter
import pandas as pd

In [12]:
full_path = r"C:\Users\sujat\.cache\kagglehub\datasets\thoughtvector\customer-support-on-twitter\versions\10\twcs\twcs.csv"

In [14]:
brand_response_counts = Counter()

for chunk in pd.read_csv(
    full_path,
    usecols=["author_id", "inbound"],
    chunksize=100_000
):
    brand_rows = chunk[chunk["inbound"] == False]
    brand_response_counts.update(
        brand_rows["author_id"].astype(str)
    )

brand_response_counts.most_common(20)

[('AmazonHelp', 169840),
 ('AppleSupport', 106860),
 ('Uber_Support', 56270),
 ('SpotifyCares', 43265),
 ('Delta', 42253),
 ('Tesco', 38573),
 ('AmericanAir', 36764),
 ('TMobileHelp', 34317),
 ('comcastcares', 33031),
 ('British_Airways', 29361),
 ('SouthwestAir', 28977),
 ('VirginTrains', 27817),
 ('Ask_Spectrum', 25860),
 ('XboxSupport', 24557),
 ('sprintcare', 22381),
 ('hulu_support', 21872),
 ('sainsburys', 19466),
 ('GWRHelp', 19364),
 ('AskPlayStation', 19098),
 ('ChipotleTweets', 18749)]